CREATE TABLE `agendamentos` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`Cliente` VARCHAR(255) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`Data` DATE NOT NULL,
	`Horario` TIME NOT NULL,
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=42
;
